### PR TITLE
Load ToricVarieties_project upon initialization

### PR DESCRIPTION
**Pull request by HereAround**

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
I only try downloading those repositories that are necessary for `CapAndHomalg` to start. And I only do this in case these repositories were deleted by the user on purpose to allow a fresh start. Such users will usually know that they have to download the remaining packages for full functionality. By your previous PR `ToricVarieties_project` is downloaded during installation, i.e., this PR is not necessary.

**Comment by HereAround** [comment]
Here is what I experience:
- By my last PR, `ToricVarieties_prjoject` is downloadable (i.e. the necessary variables in CapAndHomalg.jl are set accordingly), but it is not downloaded automatically.
- This PR goes one step further, in that it automatically downloads the `ToricVarieties_project` upon installation of this Julia package.

**Comment by mohamed-barakat** [comment]
You are right in your observation, that it is not downloaded automatically if you already have `CapAndHomalg`. But if you either
1. make a fresh install or
2. use `UpdateAllPackagesFromHomalgProject()` (which is expected from a user already having the package but asking for new functionality)

it will automatically be downloaded :)

**Comment by HereAround** [comment]
The last time I tried, 1. was not working for me. This is why I opened this PR.

My recollection is that I removed all JuliaPackages at that time, i.e. removed .julia in my home folder. In this sense, a fresh install. But please correct if I am overlooking some `Julia` basics.

If you feel uneasy with having this merged now, maybe we can come back to it later? E.g. once `ToricVarieties` executes in one way or another in `Julia`. (More on this separately...)

**Comment by mohamed-barakat** [comment]
Did you `dev CapAndHomalg` or `add CapAndHomalg`. The latter can only work after a release with your last PR, which I have just triggered :)

**Comment by mohamed-barakat** [comment]
You can see from the code, that there is no difference between `ToricVarieties_project` and `HigherHomologicalAlgebra` or any of the many other packages and they all get correctly installed.

**Comment by HereAround** [comment]
> Did you `dev CapAndHomalg` or `add CapAndHomalg`. The latter can only work after a release with your last PR, which I have just triggered :)

I used 'add CapAndHomalg'. Maybe this is the issue then.

**Comment by mohamed-barakat** [comment]
Then your new PR wouldn't even solve the problem. After a couple of minutes, the release of `CapAndHomalg` will be ready and `ToricVarities_project` will be officially supported :)

**Comment by HereAround** [comment]
Maybe we are talking cross purpose. Here is my recollection (a couple of weeks old already) of the beginning of debugging `ToricVarieties` in `Julia`.
- Pkg.add( "CapAndHomalg" ): Does not have the latest PRs in it and thus no `ToricVarieties`.
- Pig.develop( path = "clone of current master" ): After installation, the pkg subdirectory contains exactly two folders, namely `homalg_project` and `CAP_project`.
- Pkg.develop( path = "this branch" ): Now, after the installation, the pkg subdirectory contains `homalg_project`, `CAP_project` and `ToricVarieties_project`.

Irrespective, I cannot seem to find `HigherHomologicalAlgebra` in my `CapAndHomalg`.

I am using this branch of `CapAndHomalg` for debugging `ToricVarieties` in `Julia` for about the last 2 weeks now. I am pretty certain it works and (for me) to fix the availability of `ToricVarieties'.

**Comment by mohamed-barakat** [comment]
> * Pkg.add( "CapAndHomalg" ): Does not have the latest PRs in it and thus no `ToricVarieties`.

This is what I meant that the new release with your PR will be ready in a couple of minutes. It is released now.

> * Pig.develop( path = "clone of current master" ): After installation, the pkg subdirectory contains exactly two folders, namely `homalg_project` and `CAP_project`.

If you `Pkg.dev` you have to build `Pkg.build`

> * Pkg.develop( path = "this branch" ): Now, after the installation, the pkg subdirectory contains `homalg_project`, `CAP_project` and `ToricVarieties_project`.
> 
> Irrespective, I cannot seem to find `HigherHomologicalAlgebra` in my `CapAndHomalg`.

Then you didn't `build` because you `dev`ed.

See https://github.com/homalg-project/CapAndHomalg.jl#install-capandhomalgjl

**Comment by HereAround** [comment]
> > * Pkg.add( "CapAndHomalg" ): Does not have the latest PRs in it and thus no `ToricVarieties`.
> 
> This is what I meant that the new release with your PR will be ready in a couple of minutes. It is released now.
> 
> > * Pig.develop( path = "clone of current master" ): After installation, the pkg subdirectory contains exactly two folders, namely `homalg_project` and `CAP_project`.
> 
> If you `Pkg.dev` you have to build `Pkg.build`
> 
> > * Pkg.develop( path = "this branch" ): Now, after the installation, the pkg subdirectory contains `homalg_project`, `CAP_project` and `ToricVarieties_project`.
> > 
> > Irrespective, I cannot seem to find `HigherHomologicalAlgebra` in my `CapAndHomalg`.
> 
> Then you didn't `build` because you `dev`ed.
> 
> See https://github.com/homalg-project/CapAndHomalg.jl#install-capandhomalgjl

I definitely did not issue `build`. Maybe that is the step I overlooked. Will test again and then report back.

**Comment by mohamed-barakat** [comment]
If you now use `add` the build step will be automatically triggered.

**Comment by HereAround** [comment]
Long story short - you were right.

Potentially, it could be useful for others to know the steps to use the development version/distributed version. In essence, the distributed version seems to be build automatically, whereas you have to trigger this for a development version manually. The steps are thus as follows (inside Julia):
- To use the latest update of CapAndHomalg.jl, I perform the following:
(2) using Pkg
(3) Pkg.add( "CapAndHomalg" )
This seems to automatically trigger the build process. In particular, `HigherHomologicalAlgebra` and `ToricVarieties_project` are available in the .julia/packages/CapAndHomalg/versionNumber/pkg/ folder.
- To use a development version (e.g. a local clone), I proceed as follows in Julia:
(2) using Pkg
(3) Pkg.develop( path = "path/to/local/version" )
(4) Pkg.build( "CapAndHomalg" )
Step (4) seems to be crucial and is exactly what I missed previously.

It seems that this PR is not necessary, at least not now.

**Comment by mohamed-barakat** [comment]
Thanks for the investigation. I think the behavior you describe should be known for Julia packages: dev'ed packages need to be built manually. I then will close the PR.

**Comment by mohamed-barakat** [comment]
Frohe Ostern lieber Martin 🌼🐰

**Pull request closed without merging**
